# Generated by Django 2.2.3 on 2019-08-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakepy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourSecondModelNameHere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_3rd_field_name_here', models.TextField(blank=True, default='', null=True)),
                ('your_4th_field_name_here', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='YourModelNameHere',
            new_name='YourFirstModelNameHere',
        ),
    ]
